config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'
  get 'password', to: 'passwords#edit', as: 'edit_password'
  patch 'password', to: 'passwords#update'

  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'

  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  get 'org_new', to: 'orgs_new#new'
  post 'org_new', to: 'orgs_new#create'

  get 'org_update', to: 'orgs_edit#edit'
  post 'org_update', to: 'orgs_edit#update'

  get 'org_join', to: 'orgs_join#edit'
  patch 'org_join', to: 'orgs_join#update'

  get 'shifts_modify', to: 'shifts_modify#new'
  post 'shifts_modify', to: 'shifts_modify#create'

  post 'leave_org', to: 'orgs_edit#leave'
  post 'delete_shift', to: 'shifts_modify#destroy'

  get 'shifts_add', to: 'shifts_add#new'
  post 'shifts_add', to: 'shifts_add#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  # makes Current.user accessible in view files.
  attribute :user
end

app/models/organization.rb
class Organization < ApplicationRecord

   has_many :users

   # validates Organization
   validates :company, presence: true, uniqueness: true
   validates :rate, presence: true
end

app/models/shift.rb
class Shift < ApplicationRecord

     # validates Organization
     #id, userid, start(datetime), finish(datetime), breaklength
     belongs_to :user, optional: true

     validates :start, presence: true
     validates :finish, presence: true
     validates :breaklength, presence: true
  end

app/models/user.rb
class User < ApplicationRecord

   has_many :shifts
   belongs_to :organization, required: false

   # adds virtual attributes for authentication
   has_secure_password

   validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }
   validates :name, presence: true 
   validates :password, presence: true, length: { minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user
  def set_current_user
    # finds user with session data and stores it if present
    Current.user = User.find_by(id: session[:user_id]) if session[:user_id]
  end
  def require_user_logged_in!
    # allows only logged in user
    redirect_to sign_in_path, alert: 'You must be signed in' if Current.user.nil?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new; end
    def edit
      # finds user with a valid token
      @user = User.find_signed!(params[:token], purpose: 'password_reset')
      rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to sign_in_path, alert: 'Your token has expired. Please try again.'
    end
    def update
      # updates user's password
      @user = User.find_signed!(params[:token], purpose: 'password_reset')
      if @user.update(password_params)
        redirect_to sign_in_path, notice: 'Your password was reset successfully.'
        else
        flash.now[:alert] = 'Invalid Password Change.'
        render :edit
      end
    end
    private
    def password_params
      params.require(:user).permit(:password, :password_confirmation)
    end
  end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  # allows only logged in users
  before_action :require_user_logged_in!
  def edit; end
  def update
    # update user password
    if Current.user.update(password_params)
      redirect_to root_path, notice: 'Password Updated'
    else
      render :edit
    end
  end
  private
  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    # instantiates new user
    def new
      @user = User.new
    end
    def create
      @user = User.new(user_params)
      if @user.save
      # stores saved user id in a session
        session[:user_id] = @user.id
        redirect_to root_path, notice: 'Successfully created account'
      else
        flash.now[:alert] = 'Invalid sign up'
        render :new
      end
    end
    private
    def user_params
      # strong parameters
      params.require(:user).permit(:organization, :name, :email, :password, :password_confirmation)
    end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new; end
    def create
      user = User.find_by(email: params[:email])
      # finds existing user, checks to see if user can be authenticated
      if user.present? && user.authenticate(params[:password])
      # sets up user.id sessions
        session[:user_id] = user.id
        redirect_to root_path, notice: 'Logged in successfully'
      else
        flash.now[:alert] = 'Invalid email or password'
        render :new
      end
    end
    
    def destroy
      # deletes user session
      session[:user_id] = nil
      redirect_to root_path, notice: 'Logged Out'
    end
  end

app/controllers/shifts_add_controller.rb
class ShiftsAddController < ApplicationController

  def new
    @shift = Shift.new
  end

  def create

    @shift = Shift.new(user_params)
    @shift.user_id = Current.user.id

    if @shift.save
      redirect_to shifts_add_path, notice: 'Successfully added shift'
    else
      flash.now[:alert] = 'please fill out all fields'
      render :new
    end
  end

  private
  def user_params
    # strong parameters
    params.require(:shift).permit(:start, :finish, :breaklength)

  end
end

app/controllers/shifts_modify_controller.rb
class ShiftsModifyController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new
    @shift = Shift.new
  end

  def create

    @shift = Shift.new(user_params) #fix later
    @shift.user_id = Current.user.id

    if @shift.save!
      redirect_to shifts_modify_path, notice: 'Successfully added shift'
    else
      render :new
    end
  end

  def destroy
    @shift = Shift.find_by_id(params[:shift_id])
    if params[:shift_id] != nil
      @shift.destroy
      redirect_to shifts_modify_path, notice: 'shift deleted'
    else
      redirect_to shifts_modify_path, notice: 'shift failed'
    end
  end

  private
  def user_params
    # strong parameters
    params.require(:shift).permit(:start, :finish, :breaklength)

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="main">
  <div class="container">

  </div>
</div>

app/views/password_resets/edit.html.erb
<h1>Reset your password?</h1>
  <%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |f| %>
    <p>
    <%= f.label 'password:' %><br />
    <%= f.password_field :password %>
    </p>
    <p>
    <%= f.label 'password_confirmation:' %><br />
    <%= f.password_field :password_confirmation %>
    </p>
    <p>
    <%= f.submit 'Reset Password' %>
    </p>
    <br><%= link_to 'Return', root_path %>
  <% end %>

app/views/password_resets/new.html.erb
<h1>Forgot your password?</h1>
<%= form_with url: password_reset_path do |f| %>
  <p>
  <%= f.label 'email:' %><br />
  <%= f.text_field :email %>
  </p>
  <p>
  <%= f.submit 'Reset Password' %>
  </p>
<% end %>

app/views/shifts_add/new.html.erb
<%= form_with model: @shift, url: shifts_add_path do |f| %>
  <h3> Add a shift </h3>
  <p>
    <%= f.label 'Start time' %>
    <%= f.datetime_field :start %>
  </p>

  <p>
    <%= f.label 'Finish time' %>
    <%= f.datetime_field :finish %>
  </p>

  <p>
    <%= f.label 'Break length (minutes)' %>
    <%= f.number_field :breaklength %>
  </p>

  <p>
  <%= f.submit 'Submit'%><br><br>
  <%= link_to 'Return', shifts_modify_path %>
  </p>
<%end%>

app/views/shifts_modify/new.html.erb
<h2><%= Current.user.organization.company %> Shift Page</h2>

<i class="arrow right"></i>  <%= link_to 'click here', shifts_add_path %> to add a shift. <br><br>

<br><%= link_to 'Return to main page', root_path %>

<h3>Existing shifts</h3>
<%= form_with model: @shift, url: delete_shift_path do |form| %>
  <table>
    <tr>
      <th>Name</th>
      <th>Start</th>
      <th>Finish</th>
      <th>Break Length</th>
      <th>Hours Worked</th>
      <th>Shift Cost</th>
    </tr>

    <% @user_org_id = Current.user.organization_id %>
    <% @users_under_org = User.where("organization_id = ?", @user_org_id).to_a%>

    <% @users_under_org.each do |x| %>
      <% @s = Shift.where("user_id = ?", x).to_a %>

      <% @s.each do |y|%>
        <% if y != [] %>
          <tr>
            <td><%= User.find(x.id).name %></td>
            <td><%= y.start.strftime("%D %l:%M%P") %></td>
            <td><%= y.finish.strftime("%D %l:%M%P") %></td>
            <td><%= y.breaklength %></td>
            <% @shift_length_total = ((y.finish.to_time - y.start.to_time)/1.hours) %>
            <td><%= @hours_worked = ((@shift_length_total.minutes - y.breaklength)/60).round(2) %></td>
            <td><%= (@hours_worked * Current.user.organization.rate).round(3) %></td>

            <td><%= form.button :delete, name: 'shift_id', value: y.id %></td>
            </tr>
      <%end%>
    <%end%>
  <%end%>
<%end%>

app/views/welcome/index.html.erb
<body>
  <% if Current.user == nil %>
    <h1>Welcome!</h1>
    You are not currently logged in. Please log in or sign up to continue.

    <%= link_to 'Sign Up', sign_up_path %>
    or
    <%= link_to 'Login', sign_in_path %>

  <% else %>

  <h1>Welcome <%= Current.user.name %>!</h1>

    <% if Current.user.organization == nil %>

      <%= form_with model: @organization, url: org_new_path do |form| %>

      It looks like you aren't a member of any organizations.<br>
      Join an existing one or create a new one <br>
      <br>
      <i class="arrow right"></i>  <%= link_to 'join an existing organization', org_join_path %><br><br>
      <i class="arrow right"></i>  <%= link_to 'edit an existing organization', org_update_path %><br><br>

      <h3> Create A New Organisation </h3>
      <p>
      <%= form.label 'company name:'%>
      <%= form.text_field :company %><br>
      <%= form.label 'hourly rate:'%>
      <%= form.number_field :rate, step: :any, precision: 2%><br>
      <%= form.submit 'submit' %><br><br>
      </p>
      <%= link_to 'Logout', logout_path, method: :delete %><br>
      <% end %>

    <% else %>
      <p>
      You are currently a member of <%=Current.user.organization.company%>.<br><br>

      <i class="arrow right"></i>  <%= link_to 'click here', shifts_modify_path %> to go to your organizations shift page.
      <br><br>
      <i class="arrow right"></i>  <%= link_to 'click here', org_update_path %> to edit an existing organization.
      <br><br>
      <i class="arrow right"></i>  <%= link_to 'click here', org_join_path %> to join a different existing organization.
      <br><br>
      <i class="arrow right"></i>  <%= link_to 'click here', leave_org_path, method: :leave %> to leave your organization.
      <br>

      </p>
      <h3>Existing Organisations </h3>
      <%= Organization.find_each do |o| %>
      <p>
      <li style="text-indent: 40px">
        <%= o.company %>
        $<%= o.rate %>
      </li>
      </p>
      <%end%>

      <%= form_with model: @organization, url: org_new_path do |form| %>
      <h3> Create A New Organisation </h3>
      <p>
      <%= form.label 'company name:'%>
      <%= form.text_field :company %><br>
      <%= form.label 'hourly rate:'%>
      <%= form.number_field :rate %><br>
      <%= button_to 'submit', org_new_path, method: :create%>
      </p>
      <br>
      <%= link_to 'Edit Password', edit_password_path %><br>
      <%= link_to 'Logout', logout_path, method: :delete %><br><br><br>

    <%end%>
    <%end%>
    <%end%>
</body>